window.SUBSIDY_SITE_DATA = {
  updatedAt: "2026-06-21",
  companies: [
    {
      id: "qm",
      name: "株式会社クオリティマネジメント",
      shortName: "QM",
      type: "株式会社",
      representative: "矢部大",
      address: "〒193-0833 東京都八王子市めじろ台4-26-15",
      municipality: "東京都八王子市",
      industry: "経営コンサルタント",
      website: "https://qmw.co.jp/",
      employees: "廣瀬さん・大地さん",
      workRules: "有り",
      laborInsurance: "13-3-01-991120-978",
      employmentInsurance: "確認中",
      corporateNumber: "1011001035685",
      invoiceNumber: "T1011001035685",
      focus: "販路拡大、DX、IT導入、事業継続、研修・診断サービス開発",
      notes: "八王子市の市区町村制度を最優先で確認。過年度利用、市税、同一経費の重複に注意。"
    },
    {
      id: "jag",
      name: "一般社団法人ジャパンアクションギルド",
      shortName: "JAG",
      type: "一般社団法人",
      representative: "矢部大",
      address: "〒150-0043 東京都渋谷区道玄坂1丁目10番8号 渋谷道玄坂東急ビル2F-C",
      municipality: "東京都渋谷区",
      industry: "労災保険・教育、映像、スケアードストレート",
      website: "https://japanactionguild.jp/",
      employees: "要確認",
      workRules: "無し",
      laborInsurance: "13-1-07-295-769-000",
      employmentInsurance: "要確認",
      corporateNumber: "4011005008890",
      invoiceNumber: "T4011005008890",
      focus: "研修LMS、動画教材、申込管理、知財、店舗・地域連携がある場合の渋谷区制度",
      notes: "一般社団法人が対象法人格に入るか、収益事業として申請できるかを制度ごとに確認。"
    },
    {
      id: "jyoushou",
      name: "株式会社常笑",
      shortName: "常笑",
      type: "株式会社",
      representative: "堀真美",
      address: "〒160-0023 東京都新宿区西新宿三丁目3番13号 西新宿水間ビル6階",
      municipality: "東京都新宿区",
      industry: "人材派遣",
      website: "http://jyoushou.com/",
      employees: "要確認",
      workRules: "無し",
      laborInsurance: "未発行",
      employmentInsurance: "未発行",
      corporateNumber: "6011101115060",
      invoiceNumber: "",
      focus: "派遣管理、勤怠、教育、正社員化、賃上げ、省エネ設備",
      notes: "雇用系助成金は就業規則、雇用契約書、賃金台帳、出勤簿の整備が前提。"
    }
  ],
  grants: [
    {
      id: "hachioji-management",
      priority: "A",
      scope: "市区町村",
      area: "八王子市",
      name: "令和8年度 経営力強化補助金",
      status: "申請受付中",
      period: "2026-04-01から2027-01-31",
      deadline: "2027-01-31",
      companies: ["qm"],
      fit: "QMの販路拡大、BCP、特許出願、設備改良に合う。ホームページ、展示会、販促施策と相性が良い。",
      expenses: "展示会出展、商談会、海外向けパンフレット、市場調査、BCP、特許出願、設備改良・修理など",
      amount: "販路一般50万円、海外100万円、事業継続100万円",
      rate: "2/3以内など",
      howToApply: "オンライン申請。申請書をダウンロードし、公募要領を確認して提出。",
      documents: ["申請書", "見積書", "市税滞納なし確認", "会社概要", "事業計画", "過年度利用確認"],
      nextAction: "QMで販路拡大テーマを1つ決め、見積と実施時期を整理する。",
      source: "https://www.city.hachioji.tokyo.jp/kurashi/sangyo/001/p035355.html",
      sourceChecked: "2026-06-21"
    },
    {
      id: "hachioji-new-service",
      priority: "B",
      scope: "市区町村",
      area: "八王子市",
      name: "新製品・新サービス開発補助金",
      status: "公式ページで受付回確認",
      period: "公式ページで確認",
      deadline: "",
      companies: ["qm"],
      fit: "QMが新しい診断ツール、研修サービス、コンサル商品を開発する場合に候補。",
      expenses: "新製品・新サービスの開発、試作、検証、外部委託など",
      amount: "公式要確認",
      rate: "公式要確認",
      howToApply: "八王子市の補助金・公募ページから最新の募集要項を確認。",
      documents: ["開発計画", "見積書", "試作・検証計画", "市内要件の確認資料"],
      nextAction: "既存サービスの販促ではなく、新規開発として説明できる企画にする。",
      source: "https://www.city.hachioji.tokyo.jp/kurashi/sangyo/002/002/005/index.html",
      sourceChecked: "2026-06-21"
    },
    {
      id: "hachioji-price-support",
      priority: "C",
      scope: "市区町村",
      area: "八王子市",
      name: "八王子市物価高騰対応事業者支援金",
      status: "申請受付中",
      period: "2026-06-15から受付",
      deadline: "",
      companies: ["qm"],
      fit: "QMで物価高騰の影響、売上・経費要件が合う場合に確認。",
      expenses: "物価高騰影響への支援金",
      amount: "公式要確認",
      rate: "支援金",
      howToApply: "八王子市の補助金・公募ページから対象要件と申請方法を確認。",
      documents: ["市内事業実態", "売上資料", "経費資料", "市税確認"],
      nextAction: "要件に該当するかだけ早めに確認する。",
      source: "https://www.city.hachioji.tokyo.jp/kurashi/sangyo/002/002/005/index.html",
      sourceChecked: "2026-06-21"
    },
    {
      id: "shibuya-local-street",
      priority: "C",
      scope: "市区町村",
      area: "渋谷区",
      name: "店舗開業支援補助金 渋谷Local Street Project",
      status: "第2回受付予定",
      period: "第2回 2026-07-15から2026-08-31",
      deadline: "2026-08-31",
      companies: ["jag"],
      fit: "JAGが渋谷区内で来客型店舗や地域連携拠点を新規開業する場合のみ候補。現状の教育・映像事業だけでは適合は弱め。",
      expenses: "内外装工事、建物附属設備、初期広告費など",
      amount: "上限250万円",
      rate: "4/5以内",
      howToApply: "区へメールで申請希望を連絡し、返信されたアップロードURLから書類提出。",
      documents: ["交付申請書", "事業計画書", "物件資料", "見積書", "地域連携計画", "法人確認書類"],
      nextAction: "店舗・物件・商店街加入・ハチペイ導入の前提があるか確認。",
      source: "https://www.city.shibuya.tokyo.jp/jigyosha/shoko-rodo-sodan/akitempo-kassei-pj/akitempo.html",
      sourceChecked: "2026-06-21"
    },
    {
      id: "shinjuku-energy",
      priority: "C",
      scope: "市区町村",
      area: "新宿区",
      name: "令和8年度 新宿区省エネルギー及び創エネルギー機器等補助制度（事業所）",
      status: "第1期受付中",
      period: "2026-05-25から受付開始の案内あり",
      deadline: "",
      companies: ["jyoushou"],
      fit: "常笑の新宿区事業所で空調・照明などを更新する場合に候補。",
      expenses: "省エネルギー・創エネルギー機器など",
      amount: "公式要確認",
      rate: "公式要確認",
      howToApply: "新宿区の補助金ページから事業所向け制度の詳細を確認。",
      documents: ["事業所実態", "機器見積", "設置前申請", "建物所有者承諾", "設備資料"],
      nextAction: "賃貸オフィスの場合、対象機器と所有関係を確認。",
      source: "https://www.city.shinjuku.lg.jp/jigyo/index13.html",
      sourceChecked: "2026-06-21"
    },
    {
      id: "tokyo-digital-tool",
      priority: "A",
      scope: "東京都",
      area: "東京都",
      name: "中小企業デジタル導入促進補助事業",
      status: "募集中",
      period: "2026-06-11から2026-07-03",
      deadline: "2026-07-03",
      companies: ["qm", "jag", "jyoushou"],
      fit: "三社共通。QMは会計・CRM、JAGは研修申込・動画管理、常笑は派遣管理・勤怠に合う。",
      expenses: "デジタルツール本体、初期設定、カスタマイズ、運用・保守サポート",
      amount: "最大150万円",
      rate: "1/2以内。小規模企業者または環境負荷軽減ツールは2/3以内",
      howToApply: "Jグランツおよび専用フォームで電子申請。GビズIDが必要。",
      documents: ["GビズID", "見積書", "導入ツール資料", "都内事業実態", "重複補助確認"],
      nextAction: "導入したいツールと見積を先に固め、7月3日締切に間に合うか判断。",
      source: "https://www.tokyo-kosha.or.jp/support/josei/jigyo/digital-tool.html",
      sourceChecked: "2026-06-21"
    },
    {
      id: "tokyo-dx",
      priority: "A",
      scope: "東京都",
      area: "東京都",
      name: "DX推進助成金",
      status: "受付回を公式で確認",
      period: "東京都中小企業振興公社ページで確認",
      deadline: "",
      companies: ["qm", "jag", "jyoushou"],
      fit: "三社共通。システム導入だけでなく業務変革やDX戦略を説明できる場合に候補。",
      expenses: "DX戦略、業務変革、システム構築、デジタル技術導入",
      amount: "最大3,000万円級",
      rate: "区分により異なる",
      howToApply: "東京都中小企業振興公社の助成金ページで最新回を確認し、必要に応じて事前相談。",
      documents: ["会社概要", "DX課題", "見積書", "導入計画", "都内事業実態"],
      nextAction: "小規模なデジタル導入で足りるか、DX計画として大きく組むかを切り分ける。",
      source: "https://www.tokyo-kosha.or.jp/support/josei/index.html",
      sourceChecked: "2026-06-21"
    },
    {
      id: "shoryokuka-general",
      priority: "A",
      scope: "全国",
      area: "全国",
      name: "中小企業省力化投資補助金 一般型 第7回",
      status: "受付予定",
      period: "2026年7月上旬受付開始、7月下旬締切予定",
      deadline: "2026-07-31",
      companies: ["qm", "jag", "jyoushou"],
      fit: "三社共通。業務自動化、派遣管理、研修LMS、映像制作工程の省力化など。",
      expenses: "省力化設備、システム構築、AI活用、業務自動化",
      amount: "従業員数などで変動",
      rate: "類型により変動",
      howToApply: "公式サイトで公募要領を確認し、電子申請。GビズIDと事業計画が必要。",
      documents: ["GビズID", "事業計画", "見積書", "労働生産性計画", "賃上げ計画"],
      nextAction: "7月締切想定で、導入システムと見積を最優先で固める。",
      source: "https://shoryokuka.smrj.go.jp/",
      sourceChecked: "2026-06-21"
    },
    {
      id: "shoryokuka-catalog",
      priority: "A",
      scope: "全国",
      area: "全国",
      name: "中小企業省力化投資補助金 カタログ注文型",
      status: "随時受付中",
      period: "随時",
      deadline: "",
      companies: ["qm", "jag", "jyoushou"],
      fit: "三社共通。ただし業務に合うカタログ登録製品がある場合のみ。",
      expenses: "登録カタログ製品の導入",
      amount: "製品・従業員数で変動",
      rate: "類型により変動",
      howToApply: "カタログ製品と販売事業者を選定して申請。",
      documents: ["GビズID", "カタログ製品選定", "販売事業者との調整", "会社情報"],
      nextAction: "一般型と並行して、対象製品があるか確認する。",
      source: "https://shoryokuka.smrj.go.jp/catalog/",
      sourceChecked: "2026-06-21"
    },
    {
      id: "it-ai",
      priority: "A",
      scope: "全国",
      area: "全国",
      name: "デジタル化・AI導入補助金2026",
      status: "受付回を公式で確認",
      period: "公式スケジュールを随時確認",
      deadline: "",
      companies: ["qm", "jag", "jyoushou"],
      fit: "QM・常笑の業務管理、JAGの研修申込・動画管理に向く。",
      expenses: "会計、勤怠、派遣管理、CRM、予約、請求、AIツールなど",
      amount: "枠により異なる",
      rate: "枠により異なる",
      howToApply: "IT導入支援事業者・登録ITツールを確認して電子申請。",
      documents: ["GビズID", "SECURITY ACTION", "登録ITツール", "IT導入支援事業者", "見積書"],
      nextAction: "ITベンダーと登録ツールの有無を確認する。",
      source: "https://it-shien.smrj.go.jp/",
      sourceChecked: "2026-06-21"
    },
    {
      id: "jizokuka-20",
      priority: "B",
      scope: "全国",
      area: "全国",
      name: "小規模事業者持続化補助金 一般型・通常枠 第20回",
      status: "公募要領公開・受付予定",
      period: "2026-11-05から2026-12-15",
      deadline: "2026-12-15",
      companies: ["qm", "jag", "jyoushou"],
      fit: "QMは候補。常笑は従業員数次第。JAGは一般社団法人の対象可否確認。",
      expenses: "HP改修、広告、展示会、チラシ、販路開拓、動画制作",
      amount: "通常枠は原則50万円級。特例で変動",
      rate: "原則2/3など",
      howToApply: "商工会・商工会議所の支援を受け、様式4を含めて電子申請。",
      documents: ["商工会議所相談", "事業計画", "見積書", "販路開拓計画", "様式4"],
      nextAction: "秋に向けて販路開拓テーマを準備する。",
      source: "https://r6.jizokukahojokin.info/jizokukahojokin.php",
      sourceChecked: "2026-06-21"
    },
    {
      id: "career-up",
      priority: "A",
      scope: "厚労省",
      area: "全国",
      name: "キャリアアップ助成金",
      status: "随時型",
      period: "取組前に計画。各コースの期限に従う",
      deadline: "",
      companies: ["jyoushou", "qm", "jag"],
      fit: "常笑は最優先。QM・JAGも非正規雇用があれば候補。",
      expenses: "正社員化、賃金規定改定、短時間労働者の時間延長など",
      amount: "コースにより異なる",
      rate: "助成金、定額など",
      howToApply: "取組前にキャリアアップ計画を提出し、実施後に支給申請。",
      documents: ["キャリアアップ計画", "就業規則", "雇用契約書", "賃金台帳", "出勤簿"],
      nextAction: "常笑の就業規則・雇用契約・賃金台帳を整備する。",
      source: "https://www.mhlw.go.jp/stf/seisakunitsuite/bunya/koyou_roudou/part_haken/jigyounushi/career.html",
      sourceChecked: "2026-06-21"
    },
    {
      id: "human-dev",
      priority: "A",
      scope: "厚労省",
      area: "全国",
      name: "人材開発支援助成金",
      status: "随時型",
      period: "訓練開始前に計画届。コース別期限",
      deadline: "",
      companies: ["qm", "jag", "jyoushou"],
      fit: "三社共通。常笑とJAGは特に相性が良い。",
      expenses: "社員研修、派遣スタッフ教育、教育体制強化、AI・DXリスキリング",
      amount: "コースにより異なる",
      rate: "経費助成・賃金助成",
      howToApply: "訓練開始前に計画届を提出し、訓練後に支給申請。",
      documents: ["訓練計画届", "カリキュラム", "受講者名簿", "賃金台帳", "出勤簿"],
      nextAction: "教育計画を助成金仕様に合わせる。",
      source: "https://www.mhlw.go.jp/stf/seisakunitsuite/bunya/koyou_roudou/koyou/kyufukin/d01-1.html",
      sourceChecked: "2026-06-21"
    },
    {
      id: "business-improvement",
      priority: "B",
      scope: "厚労省",
      area: "全国",
      name: "業務改善助成金",
      status: "受付開始前",
      period: "2026-09-01受付開始予定",
      deadline: "",
      companies: ["qm", "jag", "jyoushou"],
      fit: "最低賃金近辺の従業員がいる事業場で候補。",
      expenses: "最低賃金引上げと生産性向上設備・システム導入",
      amount: "コースにより異なる",
      rate: "コースにより異なる",
      howToApply: "賃上げ前・設備導入前に申請。労働局の案内に従う。",
      documents: ["賃金台帳", "見積書", "事業場別最低賃金", "設備投資計画"],
      nextAction: "9月開始に向けて賃金台帳と導入設備を整理。",
      source: "https://www.mhlw.go.jp/stf/seisakunitsuite/bunya/koyou_roudou/roudoukijun/zigyonushi/shienjigyou/03.html",
      sourceChecked: "2026-06-21"
    }
  ],
  checklist: [
    { id: "gbiz", item: "GビズIDプライム", target: "3社", status: "未確認", memo: "国補助金の多くで必須。取得に時間がかかるため最優先。" },
    { id: "financials", item: "直近2期の決算書・確定申告書", target: "3社", status: "未確認", memo: "補助金・助成金・自治体申請で頻出。" },
    { id: "registry", item: "履歴事項全部証明書・法人番号", target: "3社", status: "一部確認済み", memo: "発行3か月以内指定が多い。" },
    { id: "tax", item: "納税証明・市税滞納なし証明", target: "3社", status: "未確認", memo: "自治体補助金では特に必要。" },
    { id: "rules", item: "就業規則", target: "JAG・常笑", status: "要整備", memo: "雇用系助成金では非常に重要。QMは有り。" },
    { id: "labor-docs", item: "雇用契約書・賃金台帳・出勤簿", target: "雇用がある会社", status: "未確認", memo: "キャリアアップ、人材開発、業務改善で必要。" },
    { id: "quotes", item: "導入したいIT・設備の見積", target: "3社", status: "未確認", memo: "相見積や登録ツール指定の有無に注意。" },
    { id: "plan", item: "事業計画・販路開拓計画", target: "3社", status: "未確認", memo: "採択率に直結。売上計画・ターゲット・実施体制を明確化。" },
    { id: "jag-eligibility", item: "一般社団法人の対象可否確認", target: "JAG", status: "要確認", memo: "中小企業者等の定義、収益事業性を確認。" }
  ],
  milestones: [
    { date: "2026-07-03", title: "東京都デジタル導入促進補助事業 締切", grantId: "tokyo-digital-tool", priority: "A" },
    { date: "2026-07-31", title: "省力化投資補助金 一般型 第7回 締切見込み", grantId: "shoryokuka-general", priority: "A" },
    { date: "2026-08-31", title: "渋谷Local Street Project 第2回締切", grantId: "shibuya-local-street", priority: "C" },
    { date: "2026-09-01", title: "業務改善助成金 受付開始予定", grantId: "business-improvement", priority: "B" },
    { date: "2026-12-15", title: "小規模事業者持続化補助金 第20回締切", grantId: "jizokuka-20", priority: "B" },
    { date: "2027-01-31", title: "八王子市 経営力強化補助金 締切", grantId: "hachioji-management", priority: "A" }
  ]
};
